### PR TITLE
fixed compiler flag

### PR DESCRIPTION
**Pull request by hecaex**
Fix the wrong writing of the compiler flag. (To avoid compile error)

### CODE REVIEW

**Comment by desalesouche** [comment]
what does that flag do? is there benefit from this?

**Comment by hecaex** [comment]
No benefit at all. It surpress a compiler warning interpreted as error. Due to O2 optimization it optimizes loops aggressively. It's for GCC4.8+

**Comment by desalesouche** [comment]
Ohhh! thank you will test that, i was having one kernel error compiling with O2.

By the way, does your cm13.0 twrp device tree boot?

**Comment by hecaex** [comment]
You only need that flag when you compile on both 02 or 03. 

The device tree needs some fixes, but I'm on it just quite busy with personal stuff. (We should hang this convo to Hangouts as this Pullrequest discussion is dedicated to the Kernel Flag only)

**Pull request merged**
